### ISSUE TITLE
商品の新規登録

### ISSUE THREAD

**Issue by tetsulow** [G-World-Cup/nagano-cafe#37]
No route matches {:action=>"show", :controller=>"admin/products", :id=>nil}, missing required keys: [:id]
のエラーが出ます。

**Comment by Kunibal** [comment]
controllerではpermitに:genre_idを入れたが、フォームにはジャンルを選ぶ蘭なかった

viewsファイルにこれを追加した
<div>
<div><%= f.label :genre, "ジャンルを選択" %></div>
<%= f.collection_select :genre_id, Genre.order(:name),:id,:name, include_blank: false, class: 'form-control' %>
</div>

そして、写真を追加するために、controllerでpermitにある:image_idを:imageに変更し、
viewsファイルにimage_tagを追加した。
それで、新規登録ができました。
